# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXsFw2klWSkDZe9iR6PxHzj-zyyQa6O1
"""

# app.py
def get_user_name():
    name = input("Enter your name: ")
    return name

def greet_user(name):
    print(f"Hello, {name}! Welcome to the Dockerized Python App.")

def main():
    user_name = get_user_name()
    greet_user(user_name)

if __name__ == "__main__":
    main()